"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Quicksand({ subsets: ["latin"] });
const queryClient = new QueryClient();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <GoogleOAuthProvider clientId="569006119572-am4q1670ci3fa84sd4ccv71sh1uu15ep.apps.googleusercontent.com">
            {children}
            <ReactQueryDevtools />
            <Toaster />
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
// CLIENT_ID="827944057668-90n8hlr11uh81d1vk3fp10f5f7k9b7gu.apps.googleusercontent.com"
// CLIENT_SECRET_ID="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"
